# Generated by Django 5.1.3 on 2024-11-28 23:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('locality', models.CharField(max_length=255)),
                ('state', models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], max_length=2)),
                ('country', models.CharField(default='Brazil', max_length=255)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('name', 'state', 'locality', 'country'), name='unique_neighborhood')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trust_rate', models.FloatField(default=100.0)),
                ('active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('RC', 'Recém Chegado'), ('VC', 'Vizinho Curioso'), ('VA', 'Vizinho Atento'), ('VL', 'Vizinho Colaborador'), ('VF', 'Vizinho Confiável'), ('VN', 'Vizinho Notável'), ('VI', 'Vizinho Inspirador'), ('GB', 'Guardião do Bairro'), ('SC', 'Sábio da Comunidade')], default='RC', max_length=255)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='account.account')),
                ('neighborhood', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user_profile.neighborhood')),
            ],
        ),
    ]
