# Generated by Django 5.1.3 on 2024-12-01 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_account_gender'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='biography',
            field=models.CharField(blank=True, max_length=4095, null=True),
        ),
    ]
