
POST http://localhost:8000/forum/register/
Authorization: Token ea6ba52f4d1bb15ca2037bf3a073ffc23e184354
Content-Type: application/json

{
  "title": "teste",
  "description": "This is an example description for the forum."
}

######

POST  http://localhost:8000/forum/edit/teste/ HTTP/1.1
Authorization: Token ea6ba52f4d1bb15ca2037bf3a073ffc23e184354
Content-Type: application/json

{
  "title": "natal",
  "description": "This is an example description for the forum."
}

######
GET http://localhost:8000/forum/list/?page=1
Authorization: Token a10c285f71f9d70b93e6142525f16fd1189cb752

######

GET http://localhost:8000/forum/list/?search=Exam
Authorization: Token d144351b381386263890ee25e3fb9c4a32b1d4a9

#######

POST http://localhost:8000/forum/subscribe/1/
Authorization: Token 056831ef3d4ee2f4043daaa50d7d60394aa7dd62

######

GET http://localhost:8000/forum/detail/example-forum-title-5-14/
Authorization: Token d144351b381386263890ee25e3fb9c4a32b1d4a9