# Test to get the list of all Brazilian states (UFs)
GET http://localhost:8000/user_profile/states/ HTTP/1.1
Accept: application/json

#####

GET http://localhost:8000/user_profile/cities/SP HTTP/1.1
Accept: application/json

#####

GET http://localhost:8000/user_profile/neighborhoods/SP/Piracicaba HTTP/1.1
Accept: application/json
