# Generated by Django 5.1.3 on 2024-12-03 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0001_initial'),
        ('user_profile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_date', models.DateField(editable=False)),
                ('forum', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='forum.forum')),
                ('user_profile', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to='user_profile.userprofile')),
            ],
        ),
    ]
